### ISSUE TITLE
When useSurface is set to false, the background of the boxMaterial is not transparent.

### ISSUE THREAD

**Issue by neomorphic** [JaneliaSciComp/web-vol-viewer#10] opened 2022-05-17 20:59 UTC
An example of this can bee seen in the demo application when the h5j file has been loaded, but an swc file has not been selected.

![Screen Shot 2022-05-17 at 4 58 36 PM](https://user-images.githubusercontent.com/10181/168909157-fc1fcdbd-5402-4a32-a7cf-de72a78059ec.png)

**Comment by hubbardp** [comment] 2022-05-18 15:51
May be related to a faulty graphics card?  Few if anyone else gets the gray box, and note that this next example on the original machine has a suspicious stripe in the gray box:
![Screen Shot 2022-05-18 at 9 46 46 AM](https://user-images.githubusercontent.com/32466564/169086791-170985d8-2cd8-462d-aa4d-253dd1b3548e.png)

**Comment by hubbardp** [comment] 2022-05-19 12:59
The problem went away when the alpha of each fragment was forced to 1.0 when ray casting is complete.  The alpha was already being set to 1.0 when the texture showing the rendered opaque surface (e.g., SWC) was being used, which is why the problem did not appear in that case.  The problem is now fixed in all cases by this change:
https://github.com/JaneliaSciComp/web-vol-viewer/pull/12

**Closed by hubbardp** 2022-05-19 12:59 UTC
